title: Parallel Image Compression Using Fast Fourier Transform
description: 15-418/618 Parallel Computer Architecture and Programming
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker